POST http://localhost:4004/hand-and-life/ArtisanProducts
Content-Type: application/json

{
    "email_email":"hasan.ciftci@renovaconsulting.com.tr",
    "productName":"Some Product",
    "details":"Product Details"
}

###
GET http://localhost:4004/hand-and-life/ArtisanProducts/6809e011-6be4-430c-ac6a-24d6c5c7aaaf

###

PATCH http://localhost:4004/hand-and-life/ArtisanProducts/6809e011-6be4-430c-ac6a-24d6c5c7aaaf
Content-Type: application/json

{
"productName":"Test Pr"
}

###

GET http://localhost:4004/hand-and-life/Artisans

###

GET http://localhost:4004/hand-and-life/ArtisanProfessions

###

GET http://localhost:4004/hand-and-life/ArtisanInformations