POST http://localhost:4004/hand-and-life/ArtisanProducts
Content-Type: application/json

{
    "email_email":"hasan.ciftci@renovaconsulting.com.tr",
    "productName":"Some Product",
    "details":"Product Details"
}

###
GET http://localhost:4004/hand-and-life/ArtisanProducts/6809e011-6be4-430c-ac6a-24d6c5c7aaaf

###

PATCH http://localhost:4004/hand-and-life/ArtisanProducts/6809e011-6be4-430c-ac6a-24d6c5c7aaaf
Content-Type: application/json

{
"productName":"Test Pr"
}

###

GET http://localhost:4004/hand-and-life/Artisans

###

GET http://localhost:4004/hand-and-life/ArtisanProfessions

###

GET http://localhost:4004/hand-and-life/ArtisanInformations

###

POST http://localhost:4004/hand-and-life/Categories
Content-Type: application/json

{
    "categoryID":"ABDC",
    "category":"Test"
}
###

POST http://localhost:4004/hand-and-life-integration/createOrder
Content-Type: application/json

{
"order":{
        "customerID":"mail@customer.com",
        "totalPrice":150,
        "currency":"TRY",
        "country":"TR",
        "cityCode":"34",
        "address":"Customer Addresss",
        "gsm":"+905555555555",
        "firstName":"Customer Name",
        "lastName":"Customer Surname",
        "items": [{
            "itemNo"           : 1,
            "productType"      : "E",
            "category"         :"4",
            "offerExpireBegin" : "2020-12-01T00:00:00.000Z",
            "offerExpireEnd"   : "9999-12-01T00:00:00.000Z",
            "artisanCount"     : 5,
            "productID"        : "368710c9-1d50-4b96-b91d-cfbe63100c94",
            "price"            : 10,
            "currency"         : "EUR",
            "quantity"         : "15",
            "unit"             : "ST"
        },{
            "itemNo"           : 2,
            "productType"      : "N",
            "category"         :"1",
            "offerExpireBegin" : "2020-12-01T00:00:00.000Z",
            "offerExpireEnd"   : "9999-12-01T00:00:00.000Z",
            "artisanCount"     : 2,
            "productID"        : null,
            "price"            : 10,
            "currency"         : "EUR",
            "quantity"         : "15",
            "unit"             : "ST"
        },{
            "itemNo"           : 3,
            "productType"      : "N",
            "category"         :"2",
            "offerExpireBegin" : "2020-12-01T00:00:00.000Z",
            "offerExpireEnd"   : "9999-12-01T00:00:00.000Z",
            "artisanCount"     : 5,
            "productID"        : null,
            "price"            : 10,
            "currency"         : "EUR",
            "quantity"         : "15",
            "unit"             : "ST"
        }]
    }
}
###
POST http://localhost:4004/hand-and-life-integration/saveProductProperties
Content-Type: application/json

{
    "productProperties":{
        "productID":"4f028efa-4170-4afc-abc7-27f292b5625f",
        "properties":[{
            "propertyID":1,
            "propertyValue":"55",
            "unit":"KG"
            
        },{
            "propertyID":2,
            "propertyValue":"Blue",
            "unit":""
            
        },{
            "propertyID":3,
            "propertyValue":"3x3x3",
            "unit":"CM"
        }]
    }
}
###
POST http://localhost:4004/hand-and-life/OrderItems
Content-Type: application/json

{
    "itemNo": 4,
    "orderID_orderID": "100000000",
    "productType_productTypeID": "A",
    "offerExpireBegin": "2020-12-01T00:00:00.000Z",
    "offerExpireEnd": "2020-12-05T00:00:00.000Z",
    "artisanCount": 5,
    "productID_productID": "4f028efa-4170-4afc-abc7-27f292b5625f",
    "price": 154,
    "currency_currencyCode": "TRY",
    "quantity": 15,
    "unit_unitID": "ST",
    "status_statusID": "CRTD",
    "cargoBranch": "test",
    "cargoNumber": "test2"
}

###
GET http://localhost:4004/hand-and-life-integration/getSingleProduct(productID=0d6c71df-8b30-493d-97f0-105230fd228f)

###
PATCH http://localhost:4004/hand-and-life/ArtisanOffers(orderID='100000000',offerID=0968ef68-d3e4-45f3-9b01-3d8db9e94283)
Content-Type: application/json

{
    "price":555,
    "currency_currencyCode":"TRY",
    "workDays":5,
    "details":"Details of offer",
    "status_statusID":"OFRD"
}

###
POST http://localhost:4004/hand-and-life-integration/setOfferAccepted
Content-Type: application/json

{
    "orderID":"100000000",
    "offerID":"0968ef68-d3e4-45f3-9b01-3d8db9e94283"
}

###
POST http://localhost:4004/hand-and-life-integration/updateOfferExpireDate
Content-Type: application/json

{
    "orderID":"100000000",
    "productID":"5fb02719-7749-41bd-b888-dfcf7a3593d5",
    "offerExpireBegin": "2020-12-01T00:00:00.000Z",
    "offerExpireEnd": "2025-12-05T00:00:00.000Z"
}
