###
POST http://localhost:4004/hand-and-life-integration/createOrder
Content-Type: application/json

{
    "order": {
        "customerID": "customer.mail@gmail.com",
        "totalPrice": 1505,
        "currency": "TRY",
        "country": "TR",
        "cityCode": "34",
        "address": "Hasan Çiftçi Adres",
        "gsm": "+905392435735",
        "firstName": "Hasan",
        "lastName": "Çiftçi",
        "items": [
            {
                "itemNo": 1,
                "productType": "E",
                "category": "1",
                "offerExpireBegin": "2020-12-01T00:00:00.000Z",
                "offerExpireEnd": "9999-12-01T00:00:00.000Z",
                "artisanCount": null,
                "productID": "3af14452-0313-4edd-b083-bebfc7085c4a",
                "price": 1505,
                "currency": "TRY",
                "quantity": "1",
                "unit": "ST"
            },{
                "itemNo": 2,
                "productType": "N",
                "category": "5",
                "offerExpireBegin": "2020-12-01T00:00:00.000Z",
                "offerExpireEnd": "2022-08-15T00:00:00.000Z",
                "artisanCount": 5,
                "productID": null,
                "price": null,
                "currency": null,
                "quantity": "5",
                "unit": "ST"
            },
            {
                "itemNo": 3,
                "productType": "N",
                "category": "3",
                "offerExpireBegin": "2020-12-01T00:00:00.000Z",
                "offerExpireEnd": "2022-08-15T00:00:00.000Z",
                "artisanCount": 5,
                "productID": null,
                "price": null,
                "currency": null,
                "quantity": "5",
                "unit": "ST"
            }
        ]
    }
}